### PR TITLE
Fix GitHub as Code section

### PR DESCRIPTION
**Pull request by soerenmartius**

### CODE REVIEW

**Review by mariux — CHANGES_REQUESTED** [review]
please fix ref in https://github.com/mineiros-io/terraform-github-team/pull/60/files#diff-f9444e6fdab1496608a3ee377941ab110af03f7df6bae71883cddf3c98ac84c2R403

**Comment by mariux** [comment]
> please fix ref in https://github.com/mineiros-io/terraform-github-team/pull/60/files#diff-f9444e6fdab1496608a3ee377941ab110af03f7df6bae71883cddf3c98ac84c2R403

ping @soerenmartius ;)

**Review by mariux — DISMISSED** [review]
see last comment

**Review by waxb — APPROVED** [review]
lgtm

**Pull request merged**
