### PR TITLE
format README, changes logo and badges

### PR DESCRIPTION
**Pull request by soerenmartius**

### CODE REVIEW

**Comment by mariux** [comment]
@soerenmartius please rebase

**Comment by soerenmartius** [comment]
> resolve conflicts by rebasing pls.. thx

resolved in aab1617

**Comment by mariux** [comment]
> > resolve conflicts by rebasing pls.. thx
> 
> resolved in [aab1617](https://github.com/mineiros-io/terraform-github-team/commit/aab1617df5199913e65d026551bce11e274cf0dc)

nope.. not at all still conflicts... please **rebase** to current master..

**Comment by mariux** [comment]
resolving conflicts through merges is bad as this will disable reverting single commits...

**Comment by mariux** [comment]
https://about.gitlab.com/blog/2018/06/07/keeping-git-commit-history-clean/

**Comment by soerenmartius** [comment]
> https://about.gitlab.com/blog/2018/06/07/keeping-git-commit-history-clean/

yeah makes sense. I should stop coding late hours, clearly not a good approach. Just rebased again. r4r

**Comment by soerenmartius** [comment]
> resolve conflicts by rebasing pls.. thx

resolved in 32379bb

**Comment by soerenmartius** [comment]
> Please see comment about removed makefile targets

It's still there bro - I just removed the duplicated section

**Pull request merged**
