### PR TITLE
feat: Add support for github provider 4.x

### PR DESCRIPTION
**Pull request by mariux**

### CODE REVIEW

**Comment by mariux** [comment]
rebase after fixing #31 in #32

**Review by soerenmartius — APPROVED** [review]
lgtm!

**Comment by PavelSusloparov** [comment]
Can we merge this in?

I'm trying to migrate from terraform-github to this library, however, the current state was created with github 4.9.2 provider.

```
  on .terraform/modules/admins/main.tf line 11:
  11: resource "github_team" "team" {

Instance module.admins.github_team.team data could not be decoded from the
state: unsupported attribute "create_default_maintainer".
```

**Comment by mariux** [comment]
released as v0.4.0

**Comment by PavelSusloparov** [comment]
Many thanks for that 🥳 !

**Pull request merged**
